'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Transacciones
    Public Property Id_Transacciones As Integer
    Public Property Id As String
    Public Property Carga_ID As String
    Public Property Archivo As String
    Public Property Pais As String
    Public Property PLC_ID As String
    Public Property Suc_ID As String
    Public Property Beneficiario_ID As String
    Public Property PLC_Nombre As String
    Public Property Suc_Nombre As String
    Public Property Codigo_PLC As String
    Public Property Codigo_Suc As String
    Public Property Tipo As String
    Public Property Numero As String
    Public Property Fecha As Nullable(Of Date)
    Public Property Grabacion As Nullable(Of Date)
    Public Property Vendedor As String
    Public Property Nombre_Vendedor As String
    Public Property Cliente As String
    Public Property Nombre_Cliente As String
    Public Property Mueblista As String
    Public Property Nombre_Mueblista As String
    Public Property Codigo As String
    Public Property Codigo_Masisa As String
    Public Property Descripcion_Producto As String
    Public Property Ud As String
    Public Property Cant As Nullable(Of Double)
    Public Property P_Bruto_Lista As Nullable(Of Double)
    Public Property P_Bruto_Venta As Nullable(Of Double)
    Public Property V_Bruto_Venta As Nullable(Of Double)
    Public Property Doc_Origen As String
    Public Property Marca As String
    Public Property Sup_Fam As String
    Public Property Familia As String
    Public Property Sub_Fam As String
    Public Property Cat_Masisa As Nullable(Of Double)
    Public Property Cat_Masisa_2 As Nullable(Of Double)
    Public Property Puntos As Nullable(Of Double)
    Public Property Cartola As String
    Public Property Fecha_Procesado As Nullable(Of Date)
    Public Property Procesado As Nullable(Of Boolean)
    Public Property Estado As Nullable(Of Double)
    Public Property Regla As String
    Public Property Fecha_Creacion As Nullable(Of Double)
    Public Property Rut_Final As String
    Public Property Periodo_Activo As Nullable(Of Boolean)
    Public Property Red_M As Nullable(Of Boolean)

End Class
